<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-07 05:29
=======
# Generated by Django 5.2 on 2025-05-03 08:29
>>>>>>> 464db674f306f71bb1f1c0192888868881727d73

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> 464db674f306f71bb1f1c0192888868881727d73
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('file', models.FileField(upload_to='files')),
=======
                ('file', models.FileField(upload_to='media_files')),
>>>>>>> 464db674f306f71bb1f1c0192888868881727d73
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='cars.car')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
